apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: redis
  name: redis
  selfLink: /api/v1/namespaces//services/redis
spec:
  ports:
  - name: "6379"
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    service: redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
