apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: web
  name: web
  selfLink: /api/v1/namespaces//services/web
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: web
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
